### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by OxMarco** [bahusvel/CryptoMalloc-2#2]
After having successfully compiled the library and tried executing with some common software to be found on Ubuntu, this error arises:

> Could not seek: Bad file descriptor

The VM runs Ubuntu 14.04

**Comment by bahusvel** [comment]
Could you please specify which "common software" are you using? And how are you running it?
This error is not outputted by CryptoMalloc itself. It may be due to the fact that the software passes an encrypted fd to the kernel. In which case this issue is still being worked on.

**Comment by OxMarco** [comment]
LD_PRELOAD=CryptoMalloc.so ping www.google.com
similar approach with gcc, a simple bash script and privoxy

**Comment by bahusvel** [comment]
Additionally please make sure you recompile the library CryptoMalloc is not the same as ExtraMalloc, the storage allocator works very differently.  ExtraMalloc will output this error:

``` c
if (new_offset < 0){
    perror("Could not seek");
    return NULL;
}
```

**Comment by OxMarco** [comment]
Moving the library to /usr/lib solved the issue somehow. Thank you for your support

**Comment by bahusvel** [comment]
Alternatively you can just run it with LD_PRELOAD=/FULL_PATH_TO/CryptoMalloc.so, or LD_PRELOAD=./CryptoMalloc.so, if dynamic linker "ld" doesnt see the "/" in the path it will assume the library is located in standard location such as /usr/lib/.
